import { hashText, normalizeRelativePosixPath, type PaperNote, type PaperNotesData } from './model.js';
import { escapeLatexText, markdownExcerptToLatex, markdownToLatex } from './markdown.js';
import { latexToPlainText, nearestSectionTitle, scanMarkers, type MarkerRange } from './markers.js';
import { buildSourceSelector } from './source-selector.js';
import { maskCommentsAndVerbatim, parseLatexDependencies } from './project.js';
import { pdfReadableColor } from './note-types.js';

export interface GeneratedNotes {
  json: string;
  tex: string;
  hash: string;
  data: PaperNotesData;
}

export type ProjectSources = ReadonlyMap<string, string> | Readonly<Record<string, string>>;

interface LocatedMarker {
  sourceFile: string;
  source: string;
  range: MarkerRange;
  sortOrder: number;
  inheritedSection: string;
}

/**
 * Synchronize snapshots from every managed source file and generate one stable
 * TeX fragment. A string remains accepted for the v0.2 API and unit fixtures.
 */
export function synchronizeAndGenerate(data: PaperNotesData, sourcesValue: ProjectSources | string): GeneratedNotes {
  const synchronized = structuredClone(data);
  const sources = normalizeSources(data, sourcesValue);
  const markerLocations = locateMarkers(data, sources);
  const byId = new Map<string, LocatedMarker[]>();
  for (const location of markerLocations) {
    const current = byId.get(location.range.id) ?? [];
    current.push(location);
    byId.set(location.range.id, current);
  }

  for (const note of synchronized.notes) {
    const matches = byId.get(note.id) ?? [];
    if (matches.length !== 1) {
      continue;
    }
    const location = matches[0]!;
    const { range, source } = location;
    const current = source.slice(range.contentStart, range.contentEnd);
    note.sourceFile = location.sourceFile;
    note.sourceSnapshot = current;
    note.sourceHash = hashText(current);
    note.sourceSelector = buildSourceSelector(
      source,
      range.contentStart,
      range.contentEnd,
      range.beginStart,
      range.endEnd
    );
    const localSection = nearestSectionTitle(source, range.beginStart);
    note.sectionTitle = localSection === 'Main Paper' ? location.inheritedSection : localSection;
    if (note.excerptMode === 'auto') {
      note.excerpt = makeExcerpt(current);
    }
  }

  synchronized.notes.sort((left, right) => {
    const leftLocation = uniqueLocation(byId.get(left.id));
    const rightLocation = uniqueLocation(byId.get(right.id));
    const leftPosition = leftLocation
      ? leftLocation.sortOrder
      : Number.MAX_SAFE_INTEGER;
    const rightPosition = rightLocation
      ? rightLocation.sortOrder
      : Number.MAX_SAFE_INTEGER;
    return leftPosition - rightPosition || left.id.localeCompare(right.id);
  });

  const json = `${JSON.stringify(synchronized, null, 2)}\n`;
  const hash = hashText(json);
  return { json, hash, data: synchronized, tex: renderNotesTex(synchronized, hash) };
}

export function renderNotesTex(data: PaperNotesData, dataHash: string): string {
  const lines: string[] = [
    '% !TeX root = paper_notes.tex',
    '% !TeX program = latexmk',
    `% AUTO-GENERATED BY LaTeX Paper Notes; data-sha256=${dataHash}`,
    '% Edit notes in the VS Code Paper Notes panel. Manual edits are overwritten.',
    '',
    '\\part{Main paper notes / 主文笔记}',
    ''
  ];

  for (const customType of data.customTypes) {
    lines.push(
      `\\DeclarePaperNoteCustomType{${customType.id}}{${escapeLatexText(customType.name)}}{${customType.color.slice(1)}}{${pdfReadableColor(customType.color).slice(1)}}`
    );
  }
  if (data.customTypes.length > 0) {
    lines.push('');
  }

  let currentSection = '';
  for (const note of data.notes) {
    if (note.sectionTitle !== currentSection) {
      currentSection = note.sectionTitle || 'Main Paper';
      lines.push(`\\section{${escapeLatexText(currentSection)}}`, '');
    }
    lines.push(`% source-file: ${note.sourceFile}`);
    lines.push(`\\begin{PaperNote}{main}{${note.id}}{${escapeLatexText(note.title)}}`);
    const excerpt = markdownExcerptToLatex(note.excerpt).replace(/\\par\s*/g, ' ').trim();
    lines.push(`\\SourceExcerpt{${excerpt}}`, '');
    if (note.legacyPrelude?.trim()) {
      lines.push(note.legacyPrelude.trim(), '');
    }
    for (const item of note.items) {
      const body = item.format === 'latex-legacy' ? item.content.trim() : markdownToLatex(item.content);
      if (item.type === 'custom') {
        lines.push(`\\CustomNoteItem{${item.customTypeId}}{`, body, '}', '');
      } else {
        lines.push(`\\NoteItem{${item.type}}{`, body, '}', '');
      }
    }
    if (note.legacyPostlude?.trim()) {
      lines.push(note.legacyPostlude.trim(), '');
    }
    lines.push('\\end{PaperNote}', '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function generatedHash(tex: string): string | undefined {
  return /data-sha256=([a-f0-9]{64})/.exec(tex)?.[1];
}

function normalizeSources(data: PaperNotesData, value: ProjectSources | string): Map<string, string> {
  if (typeof value === 'string') {
    return new Map([[data.project.rootFile, value]]);
  }
  if (value instanceof Map) {
    return new Map([...value].map(([path, source]) => [normalizeRelativePosixPath(path), source]));
  }
  return new Map(Object.entries(value).map(([path, source]) => [normalizeRelativePosixPath(path), source]));
}

function locateMarkers(data: PaperNotesData, sources: ReadonlyMap<string, string>): LocatedMarker[] {
  const result: LocatedMarker[] = [];
  const visited = new Set<string>();
  let sortOrder = 0;

  const visit = (sourceFile: string, inheritedSection: string): string => {
    if (visited.has(sourceFile)) {
      return inheritedSection;
    }
    visited.add(sourceFile);
    const source = sources.get(sourceFile);
    if (source === undefined) {
      return inheritedSection;
    }
    const masked = maskCommentsAndVerbatim(source);
    const events: Array<
      | { kind: 'section'; offset: number; title: string }
      | { kind: 'marker'; offset: number; range: MarkerRange }
      | { kind: 'include'; offset: number; sourceFile: string }
    > = [];
    const sectionPattern = /\\section\*?\s*\{([^{}]+)\}/g;
    let sectionMatch: RegExpExecArray | null;
    while ((sectionMatch = sectionPattern.exec(masked)) !== null) {
      events.push({ kind: 'section', offset: sectionMatch.index, title: sectionMatch[1]?.trim() || inheritedSection });
    }
    for (const range of scanMarkers(source).ranges) {
      events.push({ kind: 'marker', offset: range.beginStart, range });
    }
    try {
      for (const dependency of parseLatexDependencies(source, sourceFile)) {
        if (!dependency.dynamic && dependency.path && sources.has(dependency.path)) {
          events.push({ kind: 'include', offset: dependency.offset, sourceFile: dependency.path });
        }
      }
    } catch {
      // Project discovery reports unsafe includes; generation still handles all
      // explicitly confirmed source files below.
    }
    events.sort((left, right) => left.offset - right.offset || eventRank(left.kind) - eventRank(right.kind));
    let currentSection = inheritedSection;
    for (const event of events) {
      if (event.kind === 'section') {
        currentSection = event.title;
      } else if (event.kind === 'include') {
        currentSection = visit(event.sourceFile, currentSection);
      } else {
        result.push({ sourceFile, source, range: event.range, sortOrder: sortOrder++, inheritedSection: currentSection });
      }
    }
    return currentSection;
  };

  let section = visit(data.project.rootFile, 'Main Paper');
  for (const sourceFile of data.project.sourceFiles) {
    section = visit(sourceFile, section);
  }
  return result;
}

function eventRank(kind: 'section' | 'marker' | 'include'): number {
  return kind === 'section' ? 0 : kind === 'marker' ? 1 : 2;
}

function uniqueLocation(locations: LocatedMarker[] | undefined): LocatedMarker | undefined {
  return locations?.length === 1 ? locations[0] : undefined;
}

function makeExcerpt(source: string): string {
  const plain = latexToPlainText(source);
  return plain.length > 480 ? `${plain.slice(0, 477).trimEnd()}...` : plain;
}
